repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: db7346d375eda68a0174f2c057dd97f2fbffe030  # frozen: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/Yelp/detect-secrets.git
    rev: 70e6cf69f2d544a49729039a374d86d7b3e472d9  # frozen: v1.2.0
    hooks:
      - id: detect-secrets
        #        args: ['--baseline', '.secrets.baseline']
        exclude: |
            (?x)^(
            Cargo.lock|
            .pre-commit-config.yaml
            )$
