repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ebc15addedad713c86ef18ae9632c88e187dd0af  # frozen: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/Yelp/detect-secrets.git
    rev: e0fd07ad53dd7350cdb68e4f26cc016a801963fc  # frozen: v0.14.2
    hooks:
      - id: detect-secrets
        #        args: ['--baseline', '.secrets.baseline']
        exclude: Cargo.lock
