[package]
name = "aws_health_exporter"
version = "0.1.0"
authors = ["Vlad Vasiliu <vladvasiliun@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = { version = "~0.43.0-beta.1" }
rusoto_health = { version = "~0.43.0-beta.1" }
rusoto_signature = { version = "~0.43.0-beta.1" }
prometheus = { version = "~0.7.0", features = ["process"] }
tokio = { version = "^0.2", features = ["rt-core"] }
