[package]
name = "aws_health_exporter"
version = "0.6.0-alpha.1"
authors = ["Vlad Vasiliu"]
description = "Prometheus exporter for AWS Health events."
edition = "2021"
license-file = "COPYING"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
aws-config = "1.1"
aws-sdk-health = "1.19"
axum = { version = "0.7", default-features = false, features = ["http1", "matched-path", "tokio", "tower-log", "tracing"] }
lazy_static = { version = "~1.4" }
regex = { version = "1" }
prometheus-client = "0.22"
tokio = { version = "~1", features = ["macros", "parking_lot", "rt-multi-thread", "signal", "time"] }
tracing = "0.1"
tracing-error = { version = "^0.2", features = ["traced-error"] }
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "local-time"] }

[profile.release]
lto = true
incremental = true
codegen-units = 1
strip = true
panic = "abort"
