#!/usr/bin/env sh

GIT_TAG=$(git rev-parse --short HEAD)
VERSION=$(grep "^version = " Cargo.toml | sed -nr "s/.*\"(.*)\"/\1/p")
DATE=$(date --rfc-3339=seconds)

sed -i "1iARG GIT_TAG=\"${GIT_TAG}\"" Dockerfile
sed -i "1iARG VERSION=\"${VERSION}\"" Dockerfile
sed -i "1iARG DATE=\"${DATE}\"" Dockerfile
