#!/usr/bin/env sh

GIT_HASH=$(git rev-parse --short HEAD)
VERSION=$(grep "^version = " Cargo.toml | sed -nr "s/.*\"(.*)\"/\1/p")
BUILD_DATE=$(date --rfc-3339=seconds)

sed -i "1iARG GIT_HASH=\"${GIT_HASH}\"" Dockerfile
sed -i "1iARG VERSION=\"${VERSION}\"" Dockerfile
sed -i "1iARG BUILD_DATE=\"${BUILD_DATE}\"" Dockerfile
